# -*- coding: utf-8 -*-
"""Code-zomato trend analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vpHaKuZk0khZOGuSIAIBdqCKRpi9o56S
"""

!pip install google-play-scraper sentence-transformers pandas numpy scikit-learn tqdm

from google_play_scraper import reviews, Sort
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from datetime import datetime, timedelta
import pandas as pd
import numpy as np
from tqdm import tqdm

APP_ID = "com.application.zomato"
TARGET_DATE = "2024-08-31"
WINDOW = 30

def fetch_reviews_window(app_id, start_date, end_date, max_pages=20):
    data = []
    token = None

    for _ in range(max_pages):
        batch, token = reviews(
            app_id,
            lang='en',
            country='in',
            sort=Sort.NEWEST,
            count=200,
            continuation_token=token
        )

        if not batch:
            break

        for r in batch:
            d = r["at"].date()
            if d < start_date:
                return pd.DataFrame(data, columns=["review","date"])
            if start_date <= d <= end_date:
                data.append((r["content"], d))

        if token is None:
            break

    return pd.DataFrame(data, columns=["review","date"])

TOPICS = {
    "Delivery issue": ["late delivery","order not delivered","wrong address"],
    "Food stale": ["bad food","stale food","quality was poor"],
    "Delivery partner rude": ["delivery boy rude","rider misbehaved"],
    "Refund delay": ["refund not received","wallet not credited"],
    "App crash / lag": ["app crash","slow app","zomato lagging"]
}

model = SentenceTransformer("all-MiniLM-L6-v2")

def embed_topics():
    return list(TOPICS.keys()), model.encode([" ".join(v) for v in TOPICS.values()])

def assign_topic(text, keys, embeds, threshold=0.72):
    emb = model.encode([text])
    sims = cosine_similarity(emb, embeds)[0]
    idx = np.argmax(sims)

    if sims[idx] >= threshold:
        return keys[idx]
    else:
        TOPICS[text[:35]] = [text]
        return text[:35]

end = datetime.strptime(TARGET_DATE,"%Y-%m-%d").date()
start = end - timedelta(days=WINDOW)

df = fetch_reviews_window(APP_ID, start, end)
print("Fetched Reviews:", len(df))
df.head()

topics, embeddings = embed_topics()

assigned = []
for text in tqdm(df["review"]):
    topic = assign_topic(text, topics, embeddings)
    topics, embeddings = embed_topics()
    assigned.append(topic)

df["topic"] = assigned

# Convert df.date to pandas Timestamp
df["date"] = pd.to_datetime(df["date"])

trend = pd.pivot_table(
    df,
    index="topic",
    columns="date",
    aggfunc="size",
    fill_value=0
)

# Create full T-30 to T date range
full_dates = pd.date_range(start=start, end=end, freq="D")

# Align columns safely
trend = trend.reindex(columns=full_dates, fill_value=0)

# Sort by latest day volume
trend = trend.sort_values(by=pd.Timestamp(end), ascending=False)

trend

trend = df.pivot_table(index="topic", columns="date", aggfunc="size", fill_value=0)

full_dates = pd.date_range(start, end)
trend = trend.reindex(columns=full_dates, fill_value=0)

# Convert the 'end' date to a Timestamp object to match the DataFrame's column types
end_timestamp = pd.Timestamp(end)
trend = trend.sort_values(by=end_timestamp, ascending=False)
trend

trend.to_csv("/content/zomato_trend_aug_31.csv")
print("Saved: zomato_trend_aug_31.csv")